"""empty message

Revision ID: 6f6f772ffe5b
Revises: ed97b2863610
Create Date: 2025-02-22 00:20:13.226369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6f772ffe5b'
down_revision: Union[str, None] = 'ed97b2863610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('side_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pill_side_effect_association',
    sa.Column('pill_id', sa.Integer(), nullable=False),
    sa.Column('side_effect_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pill_id'], ['pills.id'], ),
    sa.ForeignKeyConstraint(['side_effect_id'], ['side_effects.id'], ),
    sa.PrimaryKeyConstraint('pill_id', 'side_effect_id')
    )
    op.create_table('pill_symptom_association',
    sa.Column('pill_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pill_id'], ['pills.id'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ),
    sa.PrimaryKeyConstraint('pill_id', 'symptom_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pill_symptom_association')
    op.drop_table('pill_side_effect_association')
    op.drop_table('symptoms')
    op.drop_table('side_effects')
    op.drop_table('pills')
    # ### end Alembic commands ###
